### ISSUE TITLE
TypeError: Function.prototype.toString is not generic

### ISSUE THREAD

**Issue by Xotic750** [ljharb/is-callable#2]
I was performing some tests on a module which was converted to use `isCallable` instead of `typeof` and I came across this error.
```
TypeError: Function.prototype.toString is not generic
```
Following through the test code, this is what causes the error to be thrown
```
function NameBuilder(first, last) {
    this.first = first;
    this.last = last;
}

NameBuilder.prototype = Object;

console.log(isCallable(new NameBuilder('John', 'Smith')));
```
http://jsfiddle.net/Xotic750/58hjhtsk/1/

Anyway, I did not expect `isCallable` to throw an error but return `false`. Is this fixable?

**Comment by ljharb** [comment]
Interesting - this is caused specifically because the value isn't a function, but it has a function in its `[[Prototype]]`. This is definitely fixable, I'm not sure how just yet.

**Comment by ljharb** [comment]
(aside: how do you even find these? why would anyone set a function as a `.prototype` on a constructor?? :-p)

**Comment by Xotic750** [comment]
This test originates from `commonjs-assert`, the browser version of nodes `assert`, that is used by `browserify`. As I was working on fixing some issues that I was having with `deepEqual` and `assert` (for my own modules as not every developer is as welcoming/diligent as you), and so these original tests were included to make sure nothing else was broken. It's not always just me making up weird tests. :P
