### ISSUE TITLE
`isCallable` on  `Map` and `Set` are `true`?

### ISSUE THREAD

**Issue by Xotic750** [ljharb/is-callable#3]
I've been taking a closer look at Javascript classes and saw that they have a stringTag of `[object Function]` and their type is also `function`, but `call` and `apply` are not usable as  `new` is a requirement (but `bind` does work). This got me to thinking; because I've been using `isCallable` as what I have considered a more reliable `isFunction` (old school/incorrect thinking; if it's callable it must be a function, otherwise it's not).

Then I thought, `Map` and `Set` also require `new`. So I tried `isCallable` on them and it returned `true` for both. This didn't help with my `isFunction` reconsideration. That aside, it seems logical that `isCallable` should be returning `false` (http://www.ecma-international.org/ecma-262/6.0/#sec-map-objects)?

> When called as a constructor it creates and initializes a new Map object. Map is not intended to be called as a function and will throw an exception when called in that manner.

I guess if they should be `false`, then that would be fairly difficult (impossible) to reliably detect?

**Comment by ljharb** [comment]
`isCallable` is meant to determine the existence of an internal `[[Call]]` slot, which absolutely is an "is function without new" check. Map and Set are just functions that explicitly throw when `new.target` is undefined (ie step 1 in http://www.ecma-international.org/ecma-262/6.0/#sec-map-iterable and http://www.ecma-international.org/ecma-262/6.0/#sec-set-iterable).

`function () { throw new TypeError() }` is still callable.

**Comment by Xotic750** [comment]
Ok, that makes sense. It was just my head getting its knickers in a twist with a `class` being a function object, but not really a function at the same time (if that makes sense).
