### ISSUE TITLE
ES6 Class: comments break detection.

### ISSUE THREAD

**Issue by Xotic750** [ljharb/is-callable#4]
Consider:
https://jsfiddle.net/Xotic750/vgark47f/
```
class/*kkk*/ My1 {}
class//kkk
	My2 {}

console.log(isCallable(My1)); // true
console.log(isCallable(My2)); // true
```
A possible solution, strip any comments from the string before testing.
https://jsfiddle.net/Xotic750/2q7x5gh3/
```
'use strict';

var STRIP_COMMENTS = /((\/\/.*$)|(\/\*[\s\S]*?\*\/))/mg;
var constructorRegex = /\s*class\s/;
var fnToStr = Function.prototype.toString;
var isNonES6ClassFn = function isNonES6ClassFn(value) {
	try {
		return !constructorRegex.test(fnToStr.call(value).replace(STRIP_COMMENTS, ' '));
	} catch (e) {
		return false; // not a function
	}
};

var tryFunctionObject = function tryFunctionObject(value) {
	try {
		if (constructorRegex.test(fnToStr.call(value).replace(STRIP_COMMENTS, ' '))) { return false; }
		return true;
	} catch (e) {
		return false;
	}
};
var toStr = Object.prototype.toString;
var fnClass = '[object Function]';
var genClass = '[object GeneratorFunction]';
var hasToStringTag = typeof Symbol === 'function' && typeof Symbol.toStringTag === 'symbol';

function isCallable(value) {
	if (!value) { return false; }
	if (typeof value !== 'function' && typeof value !== 'object') { return false; }
	if (hasToStringTag) { return tryFunctionObject(value); }
	if (!isNonES6ClassFn(value)) { return false; }
	var strClass = toStr.call(value);
	return strClass === fnClass || strClass === genClass;
}

class/*kkk*/ My1 {}
class//kkk
	My2 {}

console.log(isCallable(My1), isCallable(My2));
console.log(isCallable(Object), isCallable(function () {}));
```

**Comment by ljharb** [comment]
Good catch but man is that some horrible comment placement :-)

**Comment by ljharb** [comment]
Actually, in which engine did you check this? `Function.toString.call(class/*kkk*/ My1 {})` in Safari gives me `function My1() { }` which means that Safari *can't* do "class" detection, for example.

**Comment by Xotic750** [comment]
I know the chances of such poor comments are low, but they are possible. :) I tested it on V8 engines, Google Chrome and Chromium. Woah, that sucks on Safari.

**Comment by ljharb** [comment]
Firefox also can't detect it, fwiw.

**Comment by Xotic750** [comment]
Thanks for the info, and for the fix.

**Comment by Xotic750** [comment]
Just thought I'd leave you a little info. I've been looking a little further to see if there is anything by which to identify a `class` by in non-V8 environments.

In general it seems that:
```
Object.getOwnPropertyDescriptor(My1, 'prototype')
```
Return `false` for everything, whereas 
```
Object.getOwnPropertyDescriptor(function () {}, 'prototype')
```
Returns `true` for `writable`.

On FireFox, there is a `toSource` method, and if the `class` is defined with a `constructor` like:
```
class My1 {
  constructor () {}
}
```
It appears to wrap the string in parenthesis  `(function My1 () {})`

Neither are reliable methods, but I just though I'd mention what I have found so far.

**Comment by ljharb** [comment]
Thanks. Hopefully someday soon `Function#toString` will be specified more tightly so that `class` constructs are recognizable as such, but there will sadly always be browsers where it's impossible to distinguish.
